// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvknshrbmbvuijxuanbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2a25zaHJibWJ2dWlqeHVhbmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDQ4OTEsImV4cCI6MjA3MzQyMDg5MX0.M43Ttjub-XlCyAnF8qLZ6M9ID9ThX34qbxl-d8p42JM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});